# Generated by Django 5.1.2 on 2024-10-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='project_state', to='tasks.state')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='tasks.project')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='state', to='tasks.state')),
                ('asignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asignee', to='tasks.user')),
            ],
        ),
    ]
